server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.173.27:3306/tensquare_friend?characterEncoding=UTF8&useSSL=false
    username: root
    password: lty123
  jpa:
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 47.101.173.27
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: itcast